"""
Generates a synthetic CSV dataset from a user-specified column schema.
This is ONLY ever offered as a last resort in the UI, after both the
original dataset and real alternatives have failed to be found - and the
output is always labeled "SYNTHETIC DATASET - NOT THE ORIGINAL RESEARCH DATA".
"""
import os
import uuid

import numpy as np
import pandas as pd

from app.config import get_settings


def _gen_column(col_type: str, n: int, rng: np.random.Generator, categories=None):
    if col_type == "integer":
        return rng.integers(0, 1000, size=n)
    if col_type == "float":
        return np.round(rng.normal(loc=50, scale=15, size=n), 3)
    if col_type == "boolean":
        return rng.choice([True, False], size=n)
    if col_type == "category":
        cats = categories or ["A", "B", "C"]
        return rng.choice(cats, size=n)
    if col_type == "date":
        base = pd.Timestamp("2020-01-01")
        offsets = rng.integers(0, 1800, size=n)
        return [str((base + pd.Timedelta(days=int(o))).date()) for o in offsets]
    if col_type == "text":
        words = ["alpha", "beta", "gamma", "delta", "epsilon", "sample", "value", "record"]
        return [" ".join(rng.choice(words, size=3)) for _ in range(n)]
    raise ValueError(f"Unsupported column type: {col_type}")


def generate_synthetic_csv(paper_id: int, dataset_id: int, row_count: int, columns: list, seed: int) -> dict:
    """
    columns: list of {"name": str, "type": str, "categories": list[str] | None}
    Returns {"file_path": str, "preview": list[dict]}
    """
    settings = get_settings()
    rng = np.random.default_rng(seed)

    data = {}
    for col in columns:
        data[col["name"]] = _gen_column(col["type"], row_count, rng, col.get("categories"))

    df = pd.DataFrame(data)

    filename = f"synthetic_paper{paper_id}_dataset{dataset_id}_{uuid.uuid4().hex[:8]}.csv"
    file_path = os.path.join(settings.generated_dir, filename)

    # Add a clear provenance header comment as the first line of the file.
    with open(file_path, "w", encoding="utf-8", newline="") as f:
        f.write("# SYNTHETIC DATASET - NOT THE ORIGINAL RESEARCH DATA. Generated by ReXplore.\n")
        df.to_csv(f, index=False)

    preview = df.head(10).to_dict(orient="records")
    return {"file_path": file_path, "preview": preview}
